import LASTMOD from "../data/lastmod.json";

/* =========================================================================================
   One sitemap file per page template — the per-template indexation-rate instrument in
   Search Console — and an HONEST lastmod on every URL.

   The previous version defaulted lastmod to Date.now(), so every URL claimed it had been
   modified at the instant of the fetch. Two requests five seconds apart returned two
   different dates for /privacy, a page unchanged in days. That is not a missing signal, it
   is a false one, and the cost is that Google learns to disregard lastmod from this host
   entirely — which is expensive precisely for the pages where it would have been true.

   So there are two kinds of route and they are treated differently:

     DATA routes   what a reader sees is the market. lastmod is the timestamp of the data
                   the page actually displays, truncated to the hour — funding settles
                   hourly and candles close hourly, so the hour is the real resolution of
                   the change. Truncating also stops the value drifting on every request.

     CODE routes   what a reader sees changes when we change it. lastmod is the git commit
                   date of the page's own source and the data files it is built from,
                   generated by scripts/gen-lastmod.mjs and committed.

   A route with neither is emitted with no lastmod at all, which is the correct way to say
   "I do not know" — better than a plausible guess.
   ========================================================================================= */

const HOUR = 3_600_000;
/** The hour is the honest resolution for market pages; the minute would be theatre. */
export const dataStamp = (ms: number | undefined) =>
  ms ? new Date(Math.floor(ms / HOUR) * HOUR).toISOString() : undefined;

/** Committed git dates, for routes whose content is code rather than market data. */
export const codeStamp = (path: string): string | undefined => (LASTMOD as Record<string, string>)[path];

export interface Entry {
  path: string;
  /** ISO 8601. Omitted entirely when unknown. */
  lastmod?: string;
}

export function xml(entries: (Entry | string)[], base: string, fallback?: string): Response {
  const rows = entries.map((e) => {
    const { path, lastmod } = typeof e === "string" ? { path: e, lastmod: codeStamp(e) ?? fallback } : e;
    return `  <url><loc>${base}${path}</loc>${lastmod ? `<lastmod>${lastmod}</lastmod>` : ""}</url>`;
  });
  const body =
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n` +
    rows.join("\n") +
    `\n</urlset>\n`;
  return new Response(body, {
    headers: {
      "content-type": "application/xml; charset=utf-8",
      // Sitemaps must stay fetchable and reasonably fresh; a long edge cache here would
      // hide new URLs from crawlers for as long as it lives.
      "cache-control": "public, max-age=300, s-maxage=300",
    },
  });
}

/** Newest lastmod in a set, for the index to report per child sitemap. */
export const newest = (stamps: (string | undefined)[]): string | undefined => {
  const t = stamps.filter(Boolean).map((s) => Date.parse(s!)).filter(Number.isFinite);
  return t.length ? new Date(Math.max(...t)).toISOString() : undefined;
};
