/* GENERATED by scripts/stamp-worker.mjs — do not edit.
 *
 * The worker bundle the site expects to be talking to. /status compares this with the stamp
 * the deployed worker writes to KV on every run, so a worker left behind by a push is visible
 * on the page instead of showing up later as a chart that never fills.
 *
 * Regenerate with `npm run build:worker`, then deploy the worker. */
export const EXPECTED_WORKER_BUILD = "57f6dbb2516a";
