#!/usr/bin/env node
/**
 * Real last-modified dates for the routes whose content is CODE, not data.
 *
 * Taken from git: the commit that last touched the page's own source, or the data file it
 * is built from. Written to src/data/lastmod.json and committed, rather than computed at
 * build time — Cloudflare Pages does a shallow clone, so `git log` on a build machine is
 * not reliably able to answer this.
 *
 * DELIBERATELY NOT INCLUDED: the layout. A change to Base.astro touches every page's
 * markup, but a chrome tweak is not a content change and stamping forty-two URLs as
 * modified because a gridline moved is the fake signal this file exists to avoid.
 *
 *   node scripts/gen-lastmod.mjs
 */
/* AND THERE IS A --check MODE, for the same reason gen-margin-tables.mjs has one: this file is
   generated by hand and committed, so it drifts the moment anyone forgets — and forgetting is
   the normal case for a command nobody's workflow runs.
   Measured on 20 August 2026, the first time anyone looked: seven of eleven routes were
   publishing a lastmod one to two days behind the commit that actually changed them. The
   sitemap comment calls a fabricated date expensive because Google learns to disregard lastmod
   from a host that lies. A stale date is a smaller lie in a safer direction and still the same
   kind. deploy:site runs this in --check mode now, next to the margin-table check. */
import { execFileSync } from "node:child_process";
import { writeFileSync, readFileSync } from "node:fs";

const CHECK = process.argv.includes("--check");

/* /terms WAS MISSING FROM THIS LIST AND IS IN THE SITEMAP. It is prose with a source file, it
   gets edited, and it was emitted with no lastmod at all — which the sitemap comment above
   calls "the correct way to say I do not know", and it is, but we DO know. The list was
   written once and never revisited, so the page carrying the site's disclaimer was publishing
   no date on any surface. It names src/lib/site.ts as a source too, because IDENTITY is a good
   part of what a reader sees on it.

   /about WAS ADDED HERE IN THE SAME PASS AND TAKEN OUT AGAIN. It looks like prose and is not:
   it prints the covered-contract count and the open-interest floor from the live store, so it
   changes without a commit. The gate measures that rather than trusting a list, and refused
   the git date within one run. It takes a data stamp now — see PAGES_DATA in src/lib/routes.ts.
   A route belongs here because nothing but a commit can change what it shows, which is a
   narrower test than "it is mostly words". */
/** route -> the sources that genuinely determine what a reader sees on it */
const ROUTES = {
  "/terms": ["src/pages/terms.astro", "src/lib/site.ts"],
  "/methodology": ["src/pages/methodology/index.astro"],
  "/methodology/liquidations": ["src/pages/methodology/liquidations.astro"],
  "/data-sources": ["src/pages/data-sources.astro"],
  "/privacy": ["src/pages/privacy.astro"],
  "/tools": ["src/pages/tools/index.astro"],
  "/tools/position-size": ["src/pages/tools/position-size.astro", "src/lib/margin.ts"],
  "/tools/leverage": ["src/pages/tools/leverage.astro", "src/lib/margin.ts"],
  "/tools/funding-cost": ["src/pages/tools/funding-cost.astro", "src/lib/funding.ts"],
  "/tools/funding-arbitrage": ["src/pages/tools/funding-arbitrage.astro", "src/lib/funding.ts"],
  "/unlocks": ["src/pages/unlocks.astro", "src/data/vesting-contracts.json"],
  // Frozen by design: the window never moves, so this date is the truest lastmod on the site.
  "/liquidations/sweep": ["src/pages/liquidations/sweep.astro", "src/data/sweep-2026-02.json"],
  /* The two explainers that describe a method rather than a market. Each names the library it
     explains, because a change to the arithmetic changes what the page teaches even when the
     page's own source is untouched — the margin functions and the leverage profiles are as much
     the content of these pages as the prose is. The other three explainers read the live store
     and take a data stamp; see LEARN_DATA in src/lib/routes.ts. */
  "/learn/liquidation-heatmap": ["src/pages/learn/liquidation-heatmap.astro", "src/lib/liqmap.ts"],
  "/learn/liquidation-price": ["src/pages/learn/liquidation-price.astro", "src/lib/margin.ts", "src/data/margin-tables.json"],
};

const dateOf = (files) => {
  let newest = 0;
  for (const f of files) {
    try {
      const iso = execFileSync("git", ["log", "-1", "--format=%cI", "--", f], { encoding: "utf8" }).trim();
      if (iso) newest = Math.max(newest, Date.parse(iso));
    } catch { /* a file with no history yet contributes nothing */ }
  }
  return newest || null;
};

const out = {};
for (const [route, files] of Object.entries(ROUTES)) {
  const t = dateOf(files);
  if (t) out[route] = new Date(t).toISOString();
}
const next = JSON.stringify(out, null, 2) + "\n";
if (CHECK) {
  const committed = readFileSync("src/data/lastmod.json", "utf8");
  if (committed === next) {
    console.log(`  lastmod.json current: ${Object.keys(out).length} routes match their last commit`);
  } else {
    const now = JSON.parse(committed);
    const drift = [...new Set([...Object.keys(now), ...Object.keys(out)])]
      .filter((r) => now[r] !== out[r])
      .map((r) => `    ${r}: sitemap says ${now[r] ?? "(absent)"}, git says ${out[r] ?? "(absent)"}`);
    console.error(`\n  src/data/lastmod.json has drifted from git on ${drift.length} route(s):\n${drift.join("\n")}\n\n  Run: npm run gen:lastmod\n`);
    process.exit(1);
  }
} else {
  writeFileSync("src/data/lastmod.json", next);
  for (const [r, d] of Object.entries(out)) console.log(`  ${d.slice(0, 10)}  ${r}`);
  console.log(`\n${Object.keys(out).length} routes written to src/data/lastmod.json`);
}
