#!/usr/bin/env node
/**
 * THE WORKER'S BUILD STAMP, DERIVED FROM ITS SOURCE INSTEAD OF TYPED BY HAND.
 *
 * /status carries a card comparing the build stamp the deployed worker writes to KV against
 * the one the site was built with, so a worker that has drifted behind the repository is
 * visible rather than silent. The stamp was a hand-edited string in two files with a comment
 * saying "BUMP BOTH when you change this file".
 *
 * "This file" is the hole. The worker bundles src/lib/hyperliquid.ts and src/lib/coins.ts, and
 * a change to either one changes what the worker DOES while touching neither place the stamp
 * lives. That happened twice in one day — a bounded retry added to info(), and another to
 * fetchSpot() — and /status reported "worker bundle current" both times, which is a guard
 * against staleness that goes green while stale. Precisely the failure it exists to prevent.
 *
 * So the stamp is now a hash of the worker's actual dependency closure, walked from
 * worker/ingest.ts through its relative imports. Change any file the worker really depends on
 * and the stamp changes by itself; change a file it does not and it does not, so the card
 * keeps meaning something. The two generated files are excluded from the input, or the hash
 * would be a hash of itself.
 *
 * The remaining manual step is deploying, which is exactly what the card is there to catch.
 *
 *   node scripts/stamp-worker.mjs           write the stamp files
 *   node scripts/stamp-worker.mjs --check   fail if they are not what the source implies
 */
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY = join(ROOT, "worker/ingest.ts");
const STAMP = join(ROOT, "worker/build-stamp.ts");
const EXPECT = join(ROOT, "src/lib/version.ts");

/** Every relative import reachable from the worker entry — the set that decides what it does. */
export function closure(entry, read = (p) => readFileSync(p, "utf8")) {
  const seen = new Set();
  const walk = (file) => {
    const abs = resolve(file);
    if (seen.has(abs) || abs === resolve(STAMP)) return;
    if (!existsSync(abs)) return;
    seen.add(abs);
    const src = read(abs);
    for (const m of src.matchAll(/\bfrom\s+["'](\.[^"']+)["']/g)) {
      walk(resolve(dirname(abs), m[1]));
    }
  };
  walk(entry);
  return [...seen].sort();
}

const files = closure(ENTRY);
const h = createHash("sha256");
for (const f of files) {
  h.update(relative(ROOT, f));
  h.update("\0");
  h.update(readFileSync(f));
  h.update("\0");
}
const stamp = h.digest("hex").slice(0, 12);

const stampFile = `/* GENERATED by scripts/stamp-worker.mjs — do not edit.
   A hash of the worker's dependency closure (${files.length} files), so a change to anything
   the worker actually bundles changes this by itself. See the script for why it is not typed. */
export const WORKER_BUILD = ${JSON.stringify(stamp)};
`;
const expectFile = `/* GENERATED by scripts/stamp-worker.mjs — do not edit.
 *
 * The worker bundle the site expects to be talking to. /status compares this with the stamp
 * the deployed worker writes to KV on every run, so a worker left behind by a push is visible
 * on the page instead of showing up later as a chart that never fills.
 *
 * Regenerate with \`npm run build:worker\`, then deploy the worker. */
export const EXPECTED_WORKER_BUILD = ${JSON.stringify(stamp)};
`;

if (process.argv.includes("--check")) {
  const cur = [existsSync(STAMP) ? readFileSync(STAMP, "utf8") : "", existsSync(EXPECT) ? readFileSync(EXPECT, "utf8") : ""];
  if (cur[0] !== stampFile || cur[1] !== expectFile) {
    console.error(`worker stamp is stale — source hashes to ${stamp}. Run: npm run build:worker`);
    process.exit(1);
  }
  console.log(`worker stamp ${stamp} matches its ${files.length}-file source closure`);
  process.exit(0);
}

writeFileSync(STAMP, stampFile);
writeFileSync(EXPECT, expectFile);
console.log(`worker stamp ${stamp} from ${files.length} files: ${files.map((f) => relative(ROOT, f)).join(", ")}`);
