/* GENERATED by scripts/stamp-worker.mjs — do not edit.
   A hash of the worker's dependency closure (12 files), so a change to anything
   the worker actually bundles changes this by itself. See the script for why it is not typed. */
export const WORKER_BUILD = "daadcae9a2de";
