/* GENERATED by scripts/stamp-worker.mjs — do not edit.
   A hash of the worker's dependency closure (11 files), so a change to anything
   the worker actually bundles changes this by itself. See the script for why it is not typed. */
export const WORKER_BUILD = "5a80c45af610";
